---
title: "Lecture 1"
subtitle: "Productivity and Computational Tools"
author: Tyler Ransom
date: ECON 6343, University of Oklahoma
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'

---

# Attribution

- The slides for this course are closely adapted from Ivan Rudik's [course](https://github.com/AEM7130/spring-2020) at Cornell

- Ivan has graciously distributed his materials under the MIT License

- I will also make use of some of Grant McDermott's [course materials](https://github.com/uo-ec607/lectures) at the University of Oregon

- Grant also has graciously distributed his materials under the MIT License

- My course materials will also be distributed under the MIT License

--


- If you find this class lacking in a particular detail, you can likely find that detail in Ivan's or Grant's course materials.

---

# Software prerequisites

Necessary things to download for this course:

- [Julia or JuliaPro](https://julialang.org/downloads/)

- [Git](https://git-scm.com/downloads)

- Create a [GitHub](https://github.com) account if you don't already have one


---

# What this class is about

This class is a smattering of advanced econometrics topics.

1. Understanding the usefulness of structural modeling

2. Learning the computational tools for estimating structural models

3. Advanced topics in treatment effects and measurement error models

You will practice by doing lots and lots of programming.

---

# Applicability of topics

The techniques we will cover are used in a wide variety of fields of applied microeconomics:

- Labor
- Education
- IO
- Public
- Development
- Health
- Urban/Regional
- Environmental
- Others

---

# What you need to succeed in this course

1. Previous PhD-level econometrics class (either Econometrics I or Econometrics II; preferably both)

2. Previous coding experience or willingness to spend some time learning as you go

---

# Course materials

1. Everything we use in the course will be .hi-crimson[freely available] and posted to the course GitHub (which we will discuss more about momentarily)

2. Book (free [online](https://eml.berkeley.edu/books/choice2.html)):

  1. Train (2003)

3. Various published academic papers

---

# What we will cover in the class

1. Basic computing and things you need to think about

2. Coding, version control, reproducibility, workflow

3. Estimating and simulating structural models

4. Subjective expectations models

5. Measurement error correction

6. Treatment effects

7. Machine learning

---

# What you have to do

- Come to class

- Weekly coding problem sets

- Midterm exam

- One presentation of a paper from the literature

- Write a referee report on an unpublished paper of your choosing (can be the same paper you presented)

    - Papers should be related to course material in some way




---

# Grading

- Problem sets: 50%


- Class participation: 10%


- Midterm exam: 10%


- Paper presentation: 15%


- Paper referee report: 15%

---

# Problem sets (50% in all)

- You .hi-crimson[must] use Julia and write .jl scripts, no Jupyter

- You can work in groups of up to 3, but you must turn in your own code

- Problem sets will be where you .hi-crimson[implement] the techniques we learn in class on your own,
but we will be doing our fair share of coding in class

- Along the way, I will try to teach you good programming practices


---

# Computational paper presentations (15%)

- Everyone will present a paper near the end of the semester

- The paper can apply methods we've learned about (or will learn about),
or can be a new method that we have not covered

- You must consult with me at least 1 week prior to your scheduled presentation
date to ensure the paper is appropriate for a presentation

---

# Referee report (15%)

- Part of being a scientist is reviewing others' research

- You will do a referee report of a paper of your choosing

- The paper shouldn't be published, or if it has been published, you should use the earliest pre-print version

- More details about how to do this towards the end of the semester

---

# Slides

All slides will be available on the [course GitHub page](https://github.com/OU-PhD-Econometrics/fall-2020)

--

The slides are made with R Markdown and can run Julia via the JuliaCall package, e.g.

```{julia, eval=F}
# true coefficient
bbeta = π;
# random x data
x = randn(100,1)*5 .+ 3;
# OLS data generating process
y = bbeta.*x .+ randn(100,1)*10;

# OLS estimation
bbeta_hat = inv(x'x)x'y;

println("β-hat is $(round(bbeta_hat[1],digits=3)) and the true β is $(round(bbeta,digits=3)).")
```

---

# Learning Julia

- The best way to learn a programming language is through experience

- It is also great to have a reference of commonly used functions alongside

- I recommend [this cheat sheet](https://juliadocs.github.io/Julia-Cheat-Sheet/)



